name: CD-Liara
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          PUBLIC_API_ADDRESS: ${{ secrets.PUBLIC_API_ADDRESS }}
          API_KEY: ${{ secrets.API_KEY }}
          
        run: |
          npm i -g @liara/cli@5
          liara deploy --app="aibrary-dev" --api-token="$LIARA_TOKEN" --no-app-logs